### ISSUE TITLE
scrpage2.sty not found

### ISSUE THREAD

**Issue by ghost** [novoid/LaTeX-KOMA-VWA#3]
I guess it's obsolete: [Possible solution](https://tex.stackexchange.com/questions/541766/latex-error-file-scrpage2-sty-not-found)

**Comment by novoid** [comment]
Hi,

Can you show me where `scrpage2` is still used? In [the preamble](https://github.com/novoid/LaTeX-KOMA-template/blob/master/template/preamble.tex#L435) [the change already took place](https://github.com/novoid/LaTeX-KOMA-template/commit/c182c80fec5c1ae7e6e2b1d2ff4df970698d7803#diff-5856329eed9bcd207779639b7fcbff00). Maybe I've overlooked a spot somewhere?

I'll close the issue until I spot any `scrpage2` left.
